version: '2'
services:
    person-app:
        image: person
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://person-mysql:3306/person?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=person-elasticsearch:9300
        ports:
            - 8080:8080
    person-mysql:
        extends:
            file: mysql.yml
            service: person-mysql
    person-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: person-elasticsearch
